spring:
  cache:
    type: ${SPRING_CACHE_TYPE:redis}
    redis:
      time-to-live: ${SPRING_CACHE_REDIS_TTL:120s}
      cache-null-values: false
      use-key-prefix: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

frotapro:
  security:
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGIN}
    prometheus-permit-all: false
