package br.com.frotasPro.api.domain.enums;

public enum EventoNotificacao {
    SINCRONIZACAO_PENDENTE,
    SINCRONIZACAO_CONCLUIDA,
    SINCRONIZACAO_ERRO,

    INTEGRADORA_FORA_AR,
    INTEGRADORA_RECUPERADA,

    MANUTENCAO_CRIADA,
    MANUTENCAO_ATUALIZADA,
    MANUTENCAO_APAGADA,

    PARADA_CRIADA,
    PARADA_ATUALIZADA,
    PARADA_APAGADA,

    CARGA_INICIADA,
    CARGA_FINALIZADA,

    ABASTECIMENTO_CRIADO,
    ABASTECIMENTO_ATUALIZADO,
    ABASTECIMENTO_APAGADO
}
