package br.com.frotasPro.api.domain.enums;

public enum EventoNotificacao {
    SINCRONIZACAO_PENDENTE,
    SINCRONIZACAO_CONCLUIDA,
    SINCRONIZACAO_ERRO,

    INTEGRADORA_FORA_AR,
    INTEGRADORA_RECUPERADA,

    MANUTENCAO_CRIADA,
    MANUTENCAO_ATUALIZADA,
    MANUTENCAO_APAGADA,

    PARADA_CRIADA,
    PARADA_ATUALIZADA,
    PARADA_APAGADA,

    CARGA_INICIADA,
    CARGA_FINALIZADA,

    ABASTECIMENTO_CRIADO,
    ABASTECIMENTO_ATUALIZADO,
    ABASTECIMENTO_APAGADO,

    META_FORA_DO_PRAZO,
    META_CAMINHAO_FORA,

    MULTA_CRIADA,
    MULTA_ATUALIZADA,
    MULTA_PRAZO_PAGAMENTO_VENCENDO,
    MULTA_PRAZO_RECURSO_VENCENDO,

    CNH_VENCENDO,
    DOCUMENTO_CAMINHAO_VENCENDO,
    MANUTENCAO_PREVENTIVA_VENCENDO,
    MANUTENCAO_ESTAGNADA,

    MANUTENCAO_ORCAMENTO_PENDENTE,
    MANUTENCAO_ORCAMENTO_APROVADO,
    MANUTENCAO_ORCAMENTO_REJEITADO
}
